### ISSUE TITLE
UX on mobile

### ISSUE THREAD

**Issue by benmanone** [kyletimmermans/russian-grammar-practice#1]
The UI becomes squashed and overlaps on Firefox mobile. Maybe the CSS could be changed to allow for the correct sizing on smaller screens? A button which advances to the next problem rather than a timer might also be more user friendly.

**Comment by kyletimmermans** [comment]
Thanks for letting me know about the UI issues, I'll see what I can do! I downloaded Firefox for mobile and visited the site. Is the word wrap what you mean by squashed? I've attached a screenshot of what I see. And for the button for advancing to the next question, I think it's a good idea. I've actually got a few new features I want to add soon, so I'll make sure that's one that makes it in. 

![firefox_mobile](https://github.com/rus-grammar-practice/rus-grammar-practice.github.io/assets/47165102/601f7a9c-458c-4b94-83d0-1a01c89541dd)

**Comment by benmanone** [comment]
Hi, thanks for the response. Not only the wrapping but the fact that when the answer text box is focused the question goes out of view. A screenshot is attached.![image](https://github.com/rus-grammar-practice/rus-grammar-practice.github.io/assets/65849005/553886d9-1184-4c2d-9140-dbb5f9728595)

**Comment by kyletimmermans** [comment]
Ah I see. I was able to recreate the issue by switching the toolbar location to "Bottom" which causes it to do this. Fix coming soon.

**Comment by kyletimmermans** [comment]
eaf3744 should have fixed all the UX/UI issues for mobile. You should be able to see the question and type in the answer at the same time. I'm not sure what to do with the word wrap, I could make the font a lot smaller but I think that would be hard to see.
